function escapeHTML(t){return String(null==t?"":t).replace(/[&<>"']/g,t=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[t])}function avatarOf(t){return`https://avatars.githubusercontent.com/u/${encodeURIComponent(t)}?s=64&v=4`}class Picker{constructor(t,s,{onCommit:i,placeholder:a,lookup:e,t:n}){this.key=t,this.host=s,this.onCommit=i||(()=>{}),this.lookup=e,this.t=n||((t,s)=>s),this.chips=[],this.busy=0,s.className="bm-picker",s.innerHTML=`<div class="bm-chips"><input class="bm-chip-input" type="text"
      spellcheck="false" autocomplete="off" placeholder="${escapeHTML(a)}"></div>`,this.list=s.querySelector(".bm-chips"),this.input=s.querySelector(".bm-chip-input"),this.input.addEventListener("keydown",t=>{"Enter"===t.key||","===t.key||" "===t.key?(t.preventDefault(),this.commit()):"Backspace"===t.key&&!this.input.value&&this.chips.length&&this.remove(this.chips[this.chips.length-1].raw)}),this.input.addEventListener("blur",()=>this.commit()),this.input.addEventListener("paste",t=>{var s=(t.clipboardData||window.clipboardData).getData("text");/[\s,]/.test(s)&&(t.preventDefault(),s.split(/[\s,]+/).forEach(t=>this.add(t)))}),s.addEventListener("click",t=>{var s=t.target.closest(".bm-chip-x");s?this.remove(s.dataset.raw):t.target.closest(".bm-chip")||this.input.focus()})}get ids(){return this.chips.filter(t=>"ok"===t.status).map(t=>t.id)}get entries(){return this.chips.filter(t=>"ok"===t.status).map(t=>({id:t.id,login:t.login,name:t.name}))}get settled(){return 0===this.busy&&this.chips.every(t=>"ok"===t.status)}set(t){this.chips=(t||[]).map(t=>({raw:String(t.login||t.id),id:t.id,login:t.login||"",name:t.name||"",status:"ok"})),this.paint()}clear(){this.chips=[],this.paint()}commit(){var t=this.input.value.trim();this.input.value="",t&&this.add(t)}add(t){let s=String(t).replace(/^@/,"").trim();s&&!this.chips.some(t=>t.raw.toLowerCase()===s.toLowerCase())&&(this.chips.push({raw:s,id:null,login:"",name:"",status:"checking"}),this.paint(),this.resolve(s))}remove(s){var t=this.chips.length;this.chips=this.chips.filter(t=>t.raw!==s),this.chips.length!==t&&(this.paint(),this.onCommit(this))}async resolve(s){this.busy++;var t,i=await this.lookup(s),a=(this.busy--,this.chips.find(t=>t.raw===s));a&&((t=i&&i.ok&&(i.matched||[])[0])?(a.id=t.id,a.login=t.login,a.name=t.name||"",a.status="ok"):a.status=i&&i.ok?"unknown":"error",this.paint(),this.onCommit(this))}paint(){this.list.querySelectorAll(".bm-chip").forEach(t=>t.remove());var t=this.chips.map(t=>this.chipHTML(t)).join("");this.input.insertAdjacentHTML("beforebegin",t),this.host.classList.toggle("has-unknown",this.chips.some(t=>"ok"!==t.status))}chipHTML(t){var s=this.t("remove","Remove");return"checking"===t.status?`<span class="bm-chip is-checking">
        <i class="fa-solid fa-circle-notch fa-spin" aria-hidden="true"></i>
        <span class="bm-chip-name">${escapeHTML(t.raw)}</span></span>`:"ok"!==t.status?`<span class="bm-chip is-unknown" title="${escapeHTML("error"===t.status?this.t("chip_error","Lookup failed"):this.t("chip_unknown","Not a known reader"))}">
        <i class="fa-solid fa-triangle-exclamation" aria-hidden="true"></i>
        <span class="bm-chip-name">${escapeHTML(t.raw)}</span>
        <button type="button" class="bm-chip-x" data-raw="${escapeHTML(t.raw)}"
                aria-label="${escapeHTML(s)}">
          <i class="fa-solid fa-xmark" aria-hidden="true"></i></button></span>`:`<span class="bm-chip is-ok">
      <img class="bm-chip-avatar" src="${avatarOf(t.id)}" alt="" loading="lazy">
      <span class="bm-chip-name">${escapeHTML(t.name||t.login)}</span>
      <span class="bm-chip-id">#${escapeHTML(t.id)}</span>
      <button type="button" class="bm-chip-x" data-raw="${escapeHTML(t.raw)}"
              aria-label="${escapeHTML(s)}">
        <i class="fa-solid fa-xmark" aria-hidden="true"></i></button></span>`}}export{avatarOf,Picker};