function escapeHTML(t){return String(null==t?"":t).replace(/[&<>"']/g,t=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[t])}function avatarOf(t){return`https://avatars.githubusercontent.com/u/${encodeURIComponent(t)}?s=64&v=4`}function roster(){var t=window.theme&&window.theme.backend||{};return Array.isArray(t.collaborators)?t.collaborators:[]}async function rosterLookup(t){let i=String(t||"").replace(/^[@#]/,"").trim().toLowerCase();t=roster().find(t=>String(t.id)===i||String(t.name||"").toLowerCase()===i);return{ok:!0,matched:t?[{id:Number(t.id),login:"",name:t.name||""}]:[]}}let named=new Map;function nameOf(t){let n=String(t);return named.has(n)?named.get(n):(t=(async()=>{var t=roster().find(t=>String(t.id)===n);let i="",e=t?String(t.name||""):"";try{var s,a=await fetch("https://api.github.com/user/"+encodeURIComponent(n),{headers:{Accept:"application/vnd.github+json"}});a.ok&&(s=await a.json(),i=String(s.login||""),e=e||String(s.name||""))}catch(t){}return{login:i,name:e}})(),named.set(n,t),t)}let digitsOnly=t=>/^\d+$/.test(String(t||""));class Picker{constructor(t,i,{onCommit:e,placeholder:s,lookup:a,t:n}){this.key=t,this.host=i,this.onCommit=e||(()=>{}),this.lookup=a,this.t=n||((t,i)=>i),this.chips=[],this.busy=0,i.className="bm-picker",i.innerHTML=`<div class="bm-chips"><input class="bm-chip-input" type="text"
      spellcheck="false" autocomplete="off" placeholder="${escapeHTML(s)}"></div>`,this.list=i.querySelector(".bm-chips"),this.input=i.querySelector(".bm-chip-input"),this.input.addEventListener("keydown",t=>{"Enter"===t.key||","===t.key||" "===t.key?(t.preventDefault(),this.commit()):"Backspace"===t.key&&!this.input.value&&this.chips.length&&this.remove(this.chips[this.chips.length-1].raw)}),this.input.addEventListener("blur",()=>this.commit()),this.input.addEventListener("paste",t=>{var i=(t.clipboardData||window.clipboardData).getData("text");/[\s,]/.test(i)&&(t.preventDefault(),i.split(/[\s,]+/).forEach(t=>this.add(t)))}),i.addEventListener("click",t=>{var i=t.target.closest(".bm-chip-x");i?this.remove(i.dataset.raw):t.target.closest(".bm-chip")||this.input.focus()})}get ids(){return this.chips.filter(t=>"ok"===t.status).map(t=>t.id)}get entries(){return this.chips.filter(t=>"ok"===t.status).map(t=>({id:t.id,login:t.login,name:t.name}))}get settled(){return 0===this.busy&&this.chips.every(t=>"ok"===t.status)}set(t){this.chips=(t||[]).map(t=>t&&"object"==typeof t?t:{id:t}).filter(t=>null!=t.id&&""!==t.id).map(t=>{var i=digitsOnly(t.login)?"":String(t.login||"");return{raw:String(t.id),id:Number(t.id),login:i,name:String(t.name||""),status:"ok"}}),this.paint(),this.fillNames(this.chips)}fillNames(t){t=t.filter(t=>!("ok"!==t.status||t.login&&t.name));t.length&&Promise.all(t.map(async t=>{var i=await nameOf(t.id);!t.login&&i.login&&(t.login=i.login),!t.name&&i.name&&(t.name=i.name)})).then(()=>this.paint())}clear(){this.chips=[],this.paint()}commit(){var t=this.input.value.trim();this.input.value="",t&&this.add(t)}add(t){let i=String(t).replace(/^@/,"").trim();i&&!this.chips.some(t=>t.raw.toLowerCase()===i.toLowerCase())&&(this.chips.push({raw:i,id:null,login:"",name:"",status:"checking"}),this.paint(),this.resolve(i))}remove(i){var t=this.chips.length;this.chips=this.chips.filter(t=>t.raw!==i),this.chips.length!==t&&(this.paint(),this.onCommit(this))}async resolve(i){this.busy++;var t,e=await this.lookup(i),s=(this.busy--,this.chips.find(t=>t.raw===i));s&&((t=e&&e.ok&&(e.matched||[])[0])?(s.id=Number(t.id),s.login=digitsOnly(t.login)?"":String(t.login||""),s.name=String(t.name||""),s.status="ok"):s.status=e&&e.ok?"unknown":"error",this.paint(),this.onCommit(this),t)&&this.fillNames([s])}paint(){this.list.querySelectorAll(".bm-chip").forEach(t=>t.remove());var t=this.chips.map(t=>this.chipHTML(t)).join("");this.input.insertAdjacentHTML("beforebegin",t),this.host.classList.toggle("has-unknown",this.chips.some(t=>"ok"!==t.status))}chipHTML(t){var i,e,s=this.t("remove","Remove");return"checking"===t.status?`<span class="bm-chip is-checking">
        <i class="fa-solid fa-circle-notch fa-spin" aria-hidden="true"></i>
        <span class="bm-chip-name">${escapeHTML(t.raw)}</span></span>`:"ok"!==t.status?`<span class="bm-chip is-unknown" title="${escapeHTML("error"===t.status?this.t("chip_error","Lookup failed"):this.t("chip_unknown","Not a known reader"))}">
        <i class="fa-solid fa-triangle-exclamation" aria-hidden="true"></i>
        <span class="bm-chip-name">${escapeHTML(t.raw)}</span>
        <button type="button" class="bm-chip-x" data-raw="${escapeHTML(t.raw)}"
                aria-label="${escapeHTML(s)}">
          <i class="fa-solid fa-xmark" aria-hidden="true"></i></button></span>`:`<span class="bm-chip is-ok" title="${escapeHTML([i=t.name||t.login,e=t.login&&t.login!==t.name?"@"+t.login:"","#"+t.id].filter(Boolean).join(" "))}">
      <img class="bm-chip-avatar" src="${avatarOf(t.id)}" alt="" loading="lazy">
      ${i?`<span class="bm-chip-name">${escapeHTML(i)}</span>`:""}
      ${e&&t.name?`<span class="bm-chip-id">${escapeHTML(e)}</span>`:""}
      <span class="bm-chip-id">#${escapeHTML(t.id)}</span>
      <button type="button" class="bm-chip-x" data-raw="${escapeHTML(t.raw)}"
              aria-label="${escapeHTML(s)}">
        <i class="fa-solid fa-xmark" aria-hidden="true"></i></button></span>`}}export{avatarOf,rosterLookup,Picker};