import initUtils from"./utils.js";import initTyped from"./plugins/typed.js";import initModeToggle from"./tools/lightDarkSwitch.js";import initScrollTopBottom from"./tools/scrollTopBottom.js";import initLocalSearch from"./tools/localSearch.js";import initCopyCode from"./tools/codeBlock.js";import initBookmarkNav from"./layouts/bookmarkNav.js";import initLazyLoad from"./layouts/lazyload.js";import initAutoHover from"./layouts/autoHover.js";import initMathJaxScroll from"./plugins/mathjax-scroll.js";import initInstantNotes from"./plugins/instantNotes.js";let main={themeInfo:{theme:"Redefine v"+theme.version,author:"Jason-JP-Yang",repository:"https://github.com/Jason-JP-Yang/hexo-theme-Redefine-X"},localStorageKey:"REDEFINE-X-STATUS",styleStatus:{isExpandPageWidth:!1,isDark:theme.colors.default_mode&&"dark"===theme.colors.default_mode,fontSizeLevel:0,isOpenPageAside:!0},printThemeInfo:()=>{console.log(`
+=====================================================================================+
|                                                                                     |
|      ██████╗ ███████╗██████╗ ███████╗███████╗██╗███╗   ██╗███████╗   ██╗  ██╗       |
|      ██╔══██╗██╔════╝██╔══██╗██╔════╝██╔════╝██║████╗  ██║██╔════╝   ╚██╗██╔╝       |
|      ██████╔╝█████╗  ██║  ██║█████╗  █████╗  ██║██╔██╗ ██║█████╗█████╗╚███╔╝        |
|      ██╔══██╗██╔══╝  ██║  ██║██╔══╝  ██╔══╝  ██║██║╚██╗██║██╔══╝╚════╝██╔██╗        |
|      ██║  ██║███████╗██████╔╝███████╗██║     ██║██║ ╚████║███████╗   ██╔╝ ██╗       |
|      ╚═╝  ╚═╝╚══════╝╚═════╝ ╚══════╝╚═╝     ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝  ╚═╝       |
|                                                                                     |
|                 https://github.com/Jason-JP-Yang/hexo-theme-Redefine-X              |
+=====================================================================================+
    `)},setStyleStatus:()=>{localStorage.setItem(main.localStorageKey,JSON.stringify(main.styleStatus))},getStyleStatus:()=>{var t=localStorage.getItem(main.localStorageKey);if(t){for(var o in t=JSON.parse(t),main.styleStatus)main.styleStatus[o]=t[o];return t}return null},refresh:()=>{initUtils(),initModeToggle(),initScrollTopBottom(),initBookmarkNav(),0!==theme.home_banner.subtitle.text.length&&location.pathname===config.root&&initTyped("subtitle"),!0===theme.navbar.search.enable&&initLocalSearch(),!0===theme.articles.code_block.copy&&initCopyCode(),!0===theme.articles.lazyload&&initLazyLoad({preload:!0===theme.articles.lazyload_preload}),initAutoHover(),initMathJaxScroll(),theme.home_banner?.instant_notes?.enable&&location.pathname===config.root&&initInstantNotes()}};function initMain(){main.printThemeInfo(),main.refresh()}document.addEventListener("DOMContentLoaded",initMain);try{swup.hooks.on("page:view",()=>{main.refresh()})}catch(t){}export{main,initMain};