let OPEN="is-open",UNITS=[["year",31536e3],["month",2592e3],["week",604800],["day",86400],["hour",3600],["minute",60],["second",1]];function timeAgo(e){var t=window.lang_ago||{},e=new Date(e).getTime();if(!isNaN(e)){var n,s,a,i=Math.max(0,Math.floor((Date.now()-e)/1e3));for([n,s]of UNITS)if(i>=s||"second"===n)return a=Math.floor(i/s),(t[n]||`%s ${n}s ago`).replace("%s",String(a))}return""}function escapeHTML(e){return String(null==e?"":e).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function t(e,t){return(window.theme&&window.theme.notifications_i18n||{})[e]||t}function getPanel(){return document.getElementById("notifications-panel")}function isOpen(){var e=getPanel();return!!e&&e.classList.contains(OPEN)}function setOpen(t){var e,n=getPanel();n&&(e=document.getElementById("notifications-mask"),n.classList.toggle(OPEN,t),n.setAttribute("aria-hidden",t?"false":"true"),e&&e.classList.toggle(OPEN,t),document.querySelectorAll(".notifications-bell").forEach(e=>{e.setAttribute("aria-expanded",t?"true":"false"),e.classList.toggle("is-active",t)}))}function setBadge(s){document.querySelectorAll(".notifications-bell").forEach(e=>{var t,n=e.querySelector(".bell-badge");n&&(t=Number(s)||0,n.textContent=99<t?"99+":String(t),e.classList.toggle("has-unread",0<t))})}function itemHTML(e){var t=!e.read_at,n="note"===e.type?"fa-comment-dots":"announcement"===e.type?"fa-bullhorn":"fa-file-lines";return`
    <a class="np-item${t?" is-unread":""}" href="${escapeHTML(e.url)}" data-id="${escapeHTML(e.id)}">
      <span class="np-item-icon"><i class="fa-solid ${n}" aria-hidden="true"></i></span>
      <span class="np-item-main">
        <span class="np-item-title">${escapeHTML(e.title)}</span>
        ${e.body?`<span class="np-item-body">${escapeHTML(e.body)}</span>`:""}
        <span class="np-item-time">${escapeHTML(timeAgo(e.published_at))}</span>
      </span>
    </a>`}function topicsHTML(e,n){let s=0===n.length;return e.map(e=>`<button type="button" class="np-topic${s||-1!==n.indexOf(e)?" is-on":""}" data-topic="${escapeHTML(e)}">${escapeHTML(t("topic_"+e,e))}</button>`).join("")}function render(e){var n,s,a,i=getPanel();i&&(n=i.querySelector(".np-body"),s=i.querySelector(".np-foot"),a=i.querySelector(".np-mark-read"),n)&&s&&(i.classList.toggle("is-busy",!!e.busy),setBadge(e.unread||0),a&&(a.hidden=!("following"===e.phase&&0<e.unread)),"loading"===e.phase?n.innerHTML='<div class="np-empty"><i class="fa-solid fa-circle-notch fa-spin" aria-hidden="true"></i></div>':"signed-out"===e.phase?n.innerHTML=`
      <div class="np-empty">
        <i class="fa-regular fa-bell" aria-hidden="true"></i>
        <p>${escapeHTML(t("signed_out","Sign in with GitHub to follow this blog."))}</p>
      </div>`:e.items&&0!==e.items.length?n.innerHTML=`<div class="np-list">${e.items.map(itemHTML).join("")}</div>`:n.innerHTML=`
      <div class="np-empty">
        <i class="fa-regular fa-bell-slash" aria-hidden="true"></i>
        <p>${escapeHTML("following"===e.phase?t("empty_following","Nothing yet. New posts will show up here."):t("empty","Follow the blog to get notified about new posts."))}</p>
      </div>`,i=[],"signed-out"===e.phase?i.push(`<button type="button" class="np-action np-login"><i class="fa-brands fa-github" aria-hidden="true"></i> ${escapeHTML(t("sign_in","Sign in with GitHub"))}</button>`):"not-following"===e.phase?i.push(`<button type="button" class="np-action np-follow"><i class="fa-regular fa-bell" aria-hidden="true"></i> ${escapeHTML(t("follow","Follow this blog"))}</button>`):"following"===e.phase&&(e.topics&&1<e.topics.length&&i.push(`<div class="np-topics">${topicsHTML(e.topics,e.selected||[])}</div>`),"denied"===e.pushState?i.push(`<p class="np-note">${escapeHTML(t("push_denied","Notifications are blocked in your browser — new items still appear here."))}</p>`):"insecure"===e.pushState?i.push(`<p class="np-note">${escapeHTML(t("push_insecure","Push needs a secure connection (https, or localhost) — new items still appear here."))}</p>`):"unsupported"===e.pushState?i.push(`<p class="np-note">${escapeHTML(t("push_unsupported","This browser can't receive push — new items still appear here."))}</p>`):e.needsInstall?i.push(`<p class="np-note">${escapeHTML(t("push_ios","On iPhone, add this site to your Home Screen to receive push notifications."))}</p>`):"off"===e.pushState&&i.push(`<button type="button" class="np-action np-enable-push"><i class="fa-regular fa-bell" aria-hidden="true"></i> ${escapeHTML(t("enable_push","Enable push on this device"))}</button>`),i.push(`<button type="button" class="np-unfollow">${escapeHTML(t("unfollow","Unfollow"))}</button>`)),s.innerHTML=i.join(""))}export{t,getPanel,isOpen,setOpen,setBadge,render};