import{escapeHTML,parseFrontMatter,setFrontMatterKey}from"./markdown.js";let FIELDS=[{key:"title",type:"text",group:"head",label:"Title",wide:!0},{key:"date",type:"datetime",group:"head",label:"Date",fixed:!0},{key:"updated",type:"datetime",group:"head",label:"Updated",fixed:!0},{key:"cover",type:"asset",group:"look",label:"Cover"},{key:"thumbnail",type:"asset",group:"look",label:"Thumbnail"},{key:"banner",type:"asset",group:"look",label:"Banner"},{key:"excerpt",type:"area",group:"look",label:"Excerpt",wide:!0},{key:"categories",type:"list",group:"tax",label:"Categories"},{key:"tags",type:"list",group:"tax",label:"Tags"},{key:"sticky",type:"number",group:"tax",label:"Pin weight"},{key:"mathjax",type:"toggle",group:"flags",label:"MathJax",on:!1},{key:"comment",type:"toggle",group:"flags",label:"Comments",on:!0},{key:"copyright",type:"toggle",group:"flags",label:"Copyright notice",on:!0},{key:"notify",type:"toggle",group:"flags",label:"Notify followers",on:!0},{key:"published",type:"toggle",group:"flags",label:"Published",on:!0},{key:"hidden",type:"toggle",group:"flags",label:"Hide from listings",on:!1},{key:"vault",type:"toggle",group:"vault",label:"Encrypted",on:!1}],BY_KEY=new Map(FIELDS.map(e=>[e.key,e])),HIDDEN=new Set(["layout","type","template","partial","vault_kind","vault_slug","masonry_items","masonryReactions","permalink","_content","draft","supersedes"]),GROUPS=[{id:"head",label:""},{id:"look",label:"Appearance"},{id:"tax",label:"Taxonomy"},{id:"flags",label:"Behaviour"},{id:"vault",label:"Vault"}],TRUE=/^(true|yes|on|1)$/i;function isOn(e,t){return void 0!==e&&(e=String(e).trim())?TRUE.test(e):!0===t.on}function toInputDate(e){e=String(e||"").trim().match(/^(\d{4})-(\d{2})-(\d{2})[T ]?(\d{2})?:?(\d{2})?/);return e?e[1]+`-${e[2]}-${e[3]}T${e[4]||"00"}:`+(e[5]||"00"):""}function fromInputDate(e){e=String(e||"").trim().match(/^(\d{4}-\d{2}-\d{2})T(\d{2}):(\d{2})/);return e?`${e[1]} ${e[2]}:${e[3]}:00`:""}function asList(e){return Array.isArray(e)?e.filter(Boolean):(e=String(null==e?"":e).trim())?[e]:[]}function rowText(e,t,a,s){return`<label class="ed-f ${e.wide?"is-wide":""}" data-key="${e.key}">
    <span class="ed-f-label">${a}</span>
    <input class="ed-f-input" type="${s||"text"}" data-key="${e.key}" data-kind="${e.type}"
      value="${escapeHTML(t)}" spellcheck="false"${e.fixed?" readonly disabled":""}>
  </label>`}function rowArea(e,t,a){return`<label class="ed-f is-wide" data-key="${e.key}">
    <span class="ed-f-label">${a}</span>
    <textarea class="ed-f-input" rows="2" data-key="${e.key}" data-kind="area">${escapeHTML(t)}</textarea>
  </label>`}function rowAsset(e,t,a){return`<div class="ed-f ed-f-asset" data-key="${e.key}">
    <span class="ed-f-label">${a}</span>
    <span class="ed-f-assetrow">
      <span class="ed-f-thumb" data-thumb="${e.key}"></span>
      <input class="ed-f-input" data-key="${e.key}" data-kind="asset" value="${escapeHTML(t)}" spellcheck="false">
      <button type="button" class="ed-f-pick" data-pick="${e.key}" title="${escapeHTML(a)}">
        <i class="fa-solid fa-folder-open" aria-hidden="true"></i>
      </button>
    </span>
  </div>`}function rowList(e,t,a){t=asList(t).map((e,t)=>`<span class="ed-chipv" data-i="${t}">${escapeHTML(e)}<button type="button" class="ed-chipv-x" data-drop="${t}" tabindex="-1"><i class="fa-solid fa-xmark"></i></button></span>`).join("");return`<div class="ed-f ed-f-list" data-key="${e.key}">
    <span class="ed-f-label">${a}</span>
    <span class="ed-f-chips" data-chips="${e.key}">${t}<input class="ed-f-chipadd" data-add="${e.key}" spellcheck="false" placeholder="+"></span>
  </div>`}function rowToggle(e,t,a){return`<div class="np-row ed-f-toggle" data-key="${e.key}">
    <span class="np-row-main"><span class="np-row-label">${a}</span></span>
    <button type="button" class="np-switch${t?" is-on":""}" role="switch"
      aria-checked="${t?"true":"false"}" data-toggle="${e.key}" aria-label="${a}">
      <span class="np-switch-knob"><i class="fa-solid fa-circle-notch fa-spin"></i></span>
    </button>
  </div>`}function renderRow(e,t,a){a=escapeHTML(a("f_"+e.key,e.label)),t=t[e.key];return"toggle"===e.type?rowToggle(e,isOn(t,e),a):"area"===e.type?rowArea(e,t||"",a):"asset"===e.type?rowAsset(e,t||"",a):"list"===e.type?rowList(e,t,a):"datetime"===e.type?rowText(e,toInputDate(t),a,"datetime-local"):"number"===e.type?rowText(e,t||"",a,"number"):rowText(e,null==t?"":t,a)}function createFrontCard(l,n){let r=document.createElement("section"),i=(r.className="ed-front",n.t),o=new Set(Object.keys(parseFrontMatter(l.front)));function e(){let a=parseFrontMatter(l.front);t=a;var e,t=Object.keys(t).filter(e=>!BY_KEY.has(e)&&!HIDDEN.has(e)),s=GROUPS.map(t=>{var e=FIELDS.filter(e=>e.group===t.id).map(e=>renderRow(e,a,i)).join("");return`<div class="ed-front-group" data-group="${t.id}">
        ${t.label?`<h3 class="ed-front-legend">${escapeHTML(i("g_"+t.id,t.label))}</h3>`:""}
        <div class="ed-front-grid">${e}</div>
      </div>`}).join(""),t=t.map(e=>`<label class="ed-f is-wide" data-key="${e}">
            <span class="ed-f-label">${escapeHTML(e)}<i class="fa-solid fa-asterisk ed-f-extra" title="${escapeHTML(i("extra_key","not a theme key"))}"></i></span>
            <input class="ed-f-input" data-key="${escapeHTML(e)}" data-kind="text"
              value="${escapeHTML(Array.isArray(a[e])?a[e].join(", "):a[e]||"")}" spellcheck="false">
          </label>`).join("");r.innerHTML=s+(t?`<div class="ed-front-group">
             <h3 class="ed-front-legend">${escapeHTML(i("g_other","Other"))}</h3>
             <div class="ed-front-grid">${t}</div>
           </div>`:"");for(e of r.querySelectorAll("[data-thumb]"))d(e)}function d(e){var t=e.dataset.thumb,t=r.querySelector(`input[data-key="${t}"]`),t=t?t.value.trim():"";t?(e.innerHTML='<img alt="">',n.bindImage(e.querySelector("img"),t)):e.innerHTML='<i class="fa-regular fa-image" aria-hidden="true"></i>'}function p(e,t){l.front=setFrontMatterKey(l.front,e,t),l.frontDirty=!0,null===t?o.delete(e):o.add(e),n.onChange(e,t)}function c(e){return Array.from(r.querySelectorAll(`[data-chips="${e}"] .ed-chipv`)).map(e=>e.firstChild?e.firstChild.textContent:"")}return r.addEventListener("input",e=>{var t,a,e=e.target.closest("[data-key][data-kind]");e&&(t=e.dataset.key,"datetime"===(a=e.dataset.kind)?p(t,fromInputDate(e.value)):"asset"===a?(p(t,e.value.trim()),(a=r.querySelector(`[data-thumb="${t}"]`))&&d(a)):p(t,e.value))}),r.addEventListener("click",async e=>{var t,a,s=e.target.closest("[data-toggle]");s?(e.preventDefault(),t=BY_KEY.get(s.dataset.toggle),a=!s.classList.contains("is-on"),s.classList.toggle("is-on",a),s.setAttribute("aria-checked",a?"true":"false"),(s=a)===(!0===(a=t).on)&&!o.has(a.key)||p(a.key,String(s))):(t=e.target.closest("[data-drop]"))?(e.preventDefault(),a=t.closest("[data-chips]"),t.closest(".ed-chipv").remove(),p(a.dataset.chips,c(a.dataset.chips))):(s=e.target.closest("[data-pick]"))&&(e.preventDefault(),e=await n.pickImage())&&((s=r.querySelector(`input[data-key="${s.dataset.pick}"]`)).value=e.site,s.dispatchEvent(new Event("input",{bubbles:!0})))}),r.addEventListener("keydown",e=>{var t,a,s,l=e.target.closest("[data-add]");if(l)return t=l.dataset.add,"Enter"===e.key||","===e.key?(e.preventDefault(),(s=l.value.trim())?((a=document.createElement("span")).className="ed-chipv",a.textContent=s,a.insertAdjacentHTML("beforeend",'<button type="button" class="ed-chipv-x" data-drop="x" tabindex="-1"><i class="fa-solid fa-xmark"></i></button>'),l.before(a),l.value="",void p(t,c(t))):void 0):void("Backspace"!==e.key||l.value||(s=l.previousElementSibling)&&(e.preventDefault(),s.remove(),p(t,c(t))))}),e(),{el:r,paint:e,set:function(e,t){(e=r.querySelector(`input[data-key="${e}"]`))&&e!==document.activeElement&&(e.value=null==t?"":t)}}}export{FIELDS,createFrontCard};