import{escapeHTML}from"./markdown.js";import{rowArea,rowAsset,rowText,rowToggle}from"./frontmatter.js";import{albumTitle,categories,categoryFields,isTrue,itemFields,setCategoryField,setItemField}from"./masonry-yaml.js";let ALBUM_FIELDS=[{key:"name",type:"text",group:"album",label:"Name",wide:!0},{key:"page-title",type:"text",group:"album",label:"Page title"},{key:"link",type:"text",group:"album",label:"Link"},{key:"description",type:"area",group:"album",label:"Description",wide:!0},{key:"avatar",type:"asset",group:"look",label:"Avatar"},{key:"thumbnail",type:"asset",group:"look",label:"Thumbnail"},{key:"auto-exif",type:"toggle",group:"flags",label:"Read EXIF at build time",on:!1},{key:"vault",type:"toggle",group:"flags",label:"Encrypted",on:!1}],BY_KEY=new Map(ALBUM_FIELDS.map(e=>[e.key,e])),HIDDEN=new Set(["images","draft","supersedes"]),CATEGORY_FIELDS=[{key:"has_thumbnail",type:"toggle",group:"cat",label:"Cards show a thumbnail",on:!1}],GROUPS=[{id:"album",label:""},{id:"look",label:"Appearance"},{id:"cat",label:"Category"},{id:"flags",label:"Behaviour"}],MENU_MAX=8;function isOn(e,t){return void 0!==e&&(e=String(e).trim())?isTrue(e):!0===t.on}function rowCombo(e,t,a){return`<div class="ed-f is-wide ed-f-combo" data-key="links_category">
    <span class="ed-f-label">${t}</span>
    <span class="ed-pick-field">
      <i class="fa-solid fa-folder-tree" aria-hidden="true"></i>
      <input class="ed-pick-input" data-combo spellcheck="false" autocomplete="off"
        value="${escapeHTML(e)}" placeholder="${escapeHTML(a("cat_find","Search, or type a new name"))}">
      <span class="ed-f-tag" data-combo-tag></span>
      <span class="ed-pick-menu" data-combo-menu hidden></span>
    </span>
  </div>`}function createAlbumCard(r,o){let c=document.createElement("section"),n=(c.className="ed-front ed-album",o.t),d=new Set,u=new Set,p=[];function m(){d=new Set(Object.keys(itemFields(r.item))),u=new Set(Object.keys(categoryFields(r.cat)))}function g(e,t){var a=escapeHTML(n("f_"+e.key.replace(/-/g,"_"),e.label)),t=t[e.key];return"toggle"===e.type?rowToggle(e,isOn(t,e),a):"area"===e.type?rowArea(e,t||"",a):"asset"===e.type?rowAsset(e,t||"",a):rowText(e,null==t?"":t,a)}function e(){let a=itemFields(r.item),l=categoryFields(r.cat),i=String(l.links_category||"");!(p=categories(r.doc).map(e=>String(categoryFields(e).links_category||"")).filter(Boolean)).includes(i)&&i&&p.unshift(i);var e,t=GROUPS.map(t=>{let e="";return e="cat"===t.id?(e+=rowCombo(i,escapeHTML(n("f_category","Category")),n))+CATEGORY_FIELDS.map(e=>g(e,l)).join(""):ALBUM_FIELDS.filter(e=>e.group===t.id).map(e=>g(e,a)).join(""),`<div class="ed-front-group" data-group="${t.id}">
        ${t.label?`<h3 class="ed-front-legend">${escapeHTML(n("g_"+t.id,t.label))}</h3>`:""}
        <div class="ed-front-grid">${e}</div>
      </div>`}).join(""),s=Object.keys(a).filter(e=>!BY_KEY.has(e)&&!HIDDEN.has(e)).map(e=>`<label class="ed-f is-wide" data-key="${escapeHTML(e)}">
            <span class="ed-f-label">${escapeHTML(e)}<i class="fa-solid fa-asterisk ed-f-extra" title="${escapeHTML(n("extra_key","not a theme key"))}"></i></span>
            <input class="ed-f-input" data-key="${escapeHTML(e)}" data-kind="text"
              value="${escapeHTML(a[e]||"")}" spellcheck="false">
          </label>`).join("");c.innerHTML=t+(s?`<div class="ed-front-group">
             <h3 class="ed-front-legend">${escapeHTML(n("g_other","Other"))}</h3>
             <div class="ed-front-grid">${s}</div>
           </div>`:"");for(e of c.querySelectorAll("[data-thumb]"))y(e);f(),m()}function y(e){var t=e.dataset.thumb,t=c.querySelector(`input[data-key="${CSS.escape(t)}"]`),t=t?t.value.trim():"";t?(e.innerHTML='<img alt="">',o.bindImage(e.querySelector("img"),t)):e.innerHTML='<i class="fa-regular fa-image" aria-hidden="true"></i>'}let l=()=>c.querySelector("[data-combo]"),a=()=>c.querySelector("[data-combo-menu]");function f(){var e=l(),a=c.querySelector("[data-combo-tag]");if(e&&a){let t=e.value.trim();e=p.some(e=>e===t);a.textContent=t?e?n("cat_here","Existing"):n("cat_make","New"):"",a.dataset.kind=t?e?"held":"new":""}}function i(){var e=a(),t=l();e&&t&&(t=(e=>{let t=e.trim().toLowerCase();return(t?p.filter(e=>e.toLowerCase().includes(t)):p.slice()).slice(0,MENU_MAX)})(t.value),e.innerHTML=t.length?t.map(e=>`<button type="button" class="ed-pick-hit" data-cat="${escapeHTML(e)}">
                 <i class="fa-solid fa-folder" aria-hidden="true"></i>
                 <span class="ed-pick-hit-name">${escapeHTML(e)}</span>
               </button>`).join(""):`<span class="ed-pick-blank">${escapeHTML(n("cat_none","No category matches, so this makes a new one"))}</span>`,e.hidden=!1)}function s(){var e=a();e&&(e.hidden=!0)}function k(e){s();var e=String(null==e?(l()||{}).value:e).trim(),t=String(categoryFields(r.cat).links_category||""),a=l();e?(a&&(a.value=e),f(),e!==t&&o.onCategory(e)):(a&&(a.value=t),f())}function b(e,t){var a,l,i=albumTitle(itemFields(r.item));setItemField(r.item,e,""===t?null:t),null===t||""===t?d.delete(e):d.add(e),"name"!==e&&"page-title"!==e||(a=albumTitle(itemFields(r.item)),l=String(itemFields(r.item).link||""),!a)||l&&l!==v(i)||(setItemField(r.item,"link",v(a)),h("link",v(a))),o.onChange("album",e,t)}function v(e){return e?"/masonry/"+e:""}function h(e,t){e=c.querySelector(`input[data-key="${CSS.escape(e)}"], textarea[data-key="${CSS.escape(e)}"]`);e&&e!==document.activeElement&&(e.value=null==t?"":t)}return c.addEventListener("input",e=>{var t,a;e.target.closest("[data-combo]")?(i(),f()):(e=e.target.closest("[data-key][data-kind]"))&&(t=e.dataset.key,"asset"===e.dataset.kind?(b(t,e.value.trim()),(a=c.querySelector(`[data-thumb="${CSS.escape(t)}"]`))&&y(a)):b(t,e.value))}),c.addEventListener("focusin",e=>{e.target.closest("[data-combo]")&&i()}),c.addEventListener("keydown",e=>{e.target.closest("[data-combo]")&&("Enter"===e.key&&(e.preventDefault(),k(),e.target.blur()),"Escape"===e.key)&&(e.preventDefault(),e.target.value=String(categoryFields(r.cat).links_category||""),s(),f())}),c.addEventListener("blur",e=>{e.target.closest("[data-combo]")&&setTimeout(()=>k(),0)},!0),c.addEventListener("mousedown",e=>{var t=e.target.closest("[data-cat]");t&&(e.preventDefault(),k(t.dataset.cat))}),c.addEventListener("click",async e=>{var a=e.target.closest("[data-toggle]");if(a){e.preventDefault();let t=a.dataset.toggle;var l,i=BY_KEY.get(t)||CATEGORY_FIELDS.find(e=>e.key===t);return i?(l=!a.classList.contains("is-on"),a.classList.toggle("is-on",l),a.setAttribute("aria-checked",l?"true":"false"),a="has_thumbnail"===t?"cat":"album",n=(l=l)===(!0===(i=i).on),s="cat"===a?u:d,void(n&&!s.has(i.key)||("cat"===a?(setCategoryField(r.cat,i.key,String(l)),u.add(i.key),o.onChange("category",i.key,String(l))):b(i.key,String(l))))):void 0}var s,n=e.target.closest("[data-pick]");n&&(e.preventDefault(),s=await o.pickImage())&&((a=c.querySelector(`input[data-key="${CSS.escape(n.dataset.pick)}"]`)).value=s.site,a.dispatchEvent(new Event("input",{bubbles:!0})))}),e(),{el:c,paint:e,set:h,resync:m}}export{ALBUM_FIELDS,createAlbumCard};